spring.datasource.url=jdbc:mysql://localhost:3306/many_to_many_jwt
spring.datasource.username=root
spring.datasource.password=Raushanabesec@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

springdoc.swagger-ui.path=/swagger-ui.html

logging.level.root=INFO
logging.level.com.swabhav.demo=DEBUG

# JWT configuration
app.jwt.secret=ThisIsASecretKeyForJWTAuthenticationInSpringBootManyToManyProject12345
app.jwt.expiration-ms=400000
