spring.application.name=08_StudentProfileManagementSystem_Using_OneToOne_mapping
spring.datasource.url=jdbc:mysql://localhost:3306/StudentProfile_one_to_one_demo
spring.datasource.username=Springstudent
spring.datasource.password=Raushanabesec@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true