spring.application.name=03_Hibernate_studentdemo

#1.db connection and here applicable to throughout the project
spring.datasource.url=jdbc:mysql://localhost:3306/student_db
spring.datasource.username=Springstudent
spring.datasource.password=Raushanabesec@123

# for line 8,ye nahi likhoge to manually table create krna hoga workbench me...it may be create or update
#spring.jpa.hibernate.ddl-auto=create 
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


