spring.application.name=13_StudentCourse_management_for_Frontend
spring.datasource.url=jdbc:mysql://localhost:3306/13_studentcourse_frontend
spring.datasource.username=root
spring.datasource.password=Raushanabesec@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true